INSERT INTO PRODUCT (NAME, DESCRIPTION, SKU, QUANTITY) VALUES ('Casual Shirt', 'Men Solid Casual Spread Shirt', '900671', 20);
INSERT INTO PRODUCT (NAME, DESCRIPTION, SKU, QUANTITY) VALUES ('Slim Fit Trousers', 'Slim Fit Men Beige Pure Cotton Trousers', '900771', 32);
INSERT INTO PRODUCT (NAME, DESCRIPTION, SKU, QUANTITY) VALUES ('Women EthicWear', 'Women Printed, Embellished, Checkered Rayon Straight Kurta', '900871', 17);
INSERT INTO PRODUCT (NAME, DESCRIPTION, SKU, QUANTITY) VALUES ('Fancy Caps', 'Embroidered CAP', '900971', 21);
INSERT INTO PRODUCT (NAME, DESCRIPTION, SKU, QUANTITY) VALUES ('Pack of Socks', 'Men & Women Solid Ankle Length  (Pack of 3)', '900571', 100);
INSERT INTO PRODUCT (NAME, DESCRIPTION, SKU, QUANTITY) VALUES ('Casual T-Shirt', 'Men Checkered V neck POLO T-Shirt', '900471', 0);

INSERT INTO ATTRIBUTE (NAME, IS_ACTIVE) VALUES ('Color', TRUE);
INSERT INTO ATTRIBUTE (NAME, IS_ACTIVE) VALUES ('Size', TRUE);
INSERT INTO ATTRIBUTE (NAME, IS_ACTIVE) VALUES ('Brand', TRUE);
INSERT INTO ATTRIBUTE (NAME, IS_ACTIVE) VALUES ('Seller', TRUE);
INSERT INTO ATTRIBUTE (NAME, IS_ACTIVE) VALUES ('Price', TRUE);

INSERT INTO ATTRIBUTE_VALUE (DATA, IS_ACTIVE, ATTRIBUTE_ID, PRODUCT_ID) VALUES ('Yellow', TRUE, 1, 1);
INSERT INTO ATTRIBUTE_VALUE (DATA, IS_ACTIVE, ATTRIBUTE_ID, PRODUCT_ID) VALUES ('Yellow', TRUE, 1, 1);
INSERT INTO ATTRIBUTE_VALUE (DATA, IS_ACTIVE, ATTRIBUTE_ID, PRODUCT_ID) VALUES ('Yellow', TRUE, 1, 1);
INSERT INTO ATTRIBUTE_VALUE (DATA, IS_ACTIVE, ATTRIBUTE_ID, PRODUCT_ID) VALUES ('Yellow', TRUE, 1, 1);
INSERT INTO ATTRIBUTE_VALUE (DATA, IS_ACTIVE, ATTRIBUTE_ID, PRODUCT_ID) VALUES ('Yellow', TRUE, 1, 1);
INSERT INTO ATTRIBUTE_VALUE (DATA, IS_ACTIVE, ATTRIBUTE_ID, PRODUCT_ID) VALUES ('Blue', TRUE, 1, 2);
INSERT INTO ATTRIBUTE_VALUE (DATA, IS_ACTIVE, ATTRIBUTE_ID, PRODUCT_ID) VALUES ('Blue', TRUE, 1, 2);
INSERT INTO ATTRIBUTE_VALUE (DATA, IS_ACTIVE, ATTRIBUTE_ID, PRODUCT_ID) VALUES ('Red', TRUE, 1, 3);
INSERT INTO ATTRIBUTE_VALUE (DATA, IS_ACTIVE, ATTRIBUTE_ID, PRODUCT_ID) VALUES ('Purple', TRUE, 1, 5);
INSERT INTO ATTRIBUTE_VALUE (DATA, IS_ACTIVE, ATTRIBUTE_ID, PRODUCT_ID) VALUES ('Purple', TRUE, 1, 3);
INSERT INTO ATTRIBUTE_VALUE (DATA, IS_ACTIVE, ATTRIBUTE_ID, PRODUCT_ID) VALUES ('Purple', TRUE, 1, 5);

INSERT INTO ATTRIBUTE_VALUE (DATA, IS_ACTIVE, ATTRIBUTE_ID, PRODUCT_ID) VALUES ('L', TRUE, 2, 1);
INSERT INTO ATTRIBUTE_VALUE (DATA, IS_ACTIVE, ATTRIBUTE_ID, PRODUCT_ID) VALUES ('L', TRUE, 2, 1);
INSERT INTO ATTRIBUTE_VALUE (DATA, IS_ACTIVE, ATTRIBUTE_ID, PRODUCT_ID) VALUES ('L', TRUE, 2, 3);
INSERT INTO ATTRIBUTE_VALUE (DATA, IS_ACTIVE, ATTRIBUTE_ID, PRODUCT_ID) VALUES ('M', TRUE, 2, 5);
INSERT INTO ATTRIBUTE_VALUE (DATA, IS_ACTIVE, ATTRIBUTE_ID, PRODUCT_ID) VALUES ('M', TRUE, 2, 2);
INSERT INTO ATTRIBUTE_VALUE (DATA, IS_ACTIVE, ATTRIBUTE_ID, PRODUCT_ID) VALUES ('S', TRUE, 2, 4);
INSERT INTO ATTRIBUTE_VALUE (DATA, IS_ACTIVE, ATTRIBUTE_ID, PRODUCT_ID) VALUES ('XL', TRUE, 2, 4);

INSERT INTO ATTRIBUTE_VALUE (DATA, IS_ACTIVE, ATTRIBUTE_ID, PRODUCT_ID) VALUES ('Puma', TRUE, 3, 3);
INSERT INTO ATTRIBUTE_VALUE (DATA, IS_ACTIVE, ATTRIBUTE_ID, PRODUCT_ID) VALUES ('Puma', TRUE, 3, 5);

INSERT INTO ATTRIBUTE_VALUE (DATA, IS_ACTIVE, ATTRIBUTE_ID, PRODUCT_ID) VALUES ('W', TRUE, 3, 3);
INSERT INTO ATTRIBUTE_VALUE (DATA, IS_ACTIVE, ATTRIBUTE_ID, PRODUCT_ID) VALUES ('W', TRUE, 3, 3);
INSERT INTO ATTRIBUTE_VALUE (DATA, IS_ACTIVE, ATTRIBUTE_ID, PRODUCT_ID) VALUES ('W', TRUE, 3, 3);

INSERT INTO ATTRIBUTE_VALUE (DATA, IS_ACTIVE, ATTRIBUTE_ID, PRODUCT_ID) VALUES ('Reebok', TRUE, 3, 1);
INSERT INTO ATTRIBUTE_VALUE (DATA, IS_ACTIVE, ATTRIBUTE_ID, PRODUCT_ID) VALUES ('Arrow', TRUE, 3, 1);
INSERT INTO ATTRIBUTE_VALUE (DATA, IS_ACTIVE, ATTRIBUTE_ID, PRODUCT_ID) VALUES ('VanHuesan', TRUE, 3, 1);
INSERT INTO ATTRIBUTE_VALUE (DATA, IS_ACTIVE, ATTRIBUTE_ID, PRODUCT_ID) VALUES ('RangManch', TRUE, 3, 2);
INSERT INTO ATTRIBUTE_VALUE (DATA, IS_ACTIVE, ATTRIBUTE_ID, PRODUCT_ID) VALUES ('GlobalDesi', TRUE, 3, 2);
INSERT INTO ATTRIBUTE_VALUE (DATA, IS_ACTIVE, ATTRIBUTE_ID, PRODUCT_ID) VALUES ('GlobalDesi', TRUE, 3, 2);
INSERT INTO ATTRIBUTE_VALUE (DATA, IS_ACTIVE, ATTRIBUTE_ID, PRODUCT_ID) VALUES ('GlobalDesi', TRUE, 3, 2);
INSERT INTO ATTRIBUTE_VALUE (DATA, IS_ACTIVE, ATTRIBUTE_ID, PRODUCT_ID) VALUES ('Arrow', TRUE, 3, 1);
INSERT INTO ATTRIBUTE_VALUE (DATA, IS_ACTIVE, ATTRIBUTE_ID, PRODUCT_ID) VALUES ('VanHuesan', TRUE, 3, 1);
INSERT INTO ATTRIBUTE_VALUE (DATA, IS_ACTIVE, ATTRIBUTE_ID, PRODUCT_ID) VALUES ('Raymond', TRUE, 3, 4);
INSERT INTO ATTRIBUTE_VALUE (DATA, IS_ACTIVE, ATTRIBUTE_ID, PRODUCT_ID) VALUES ('TATA', TRUE, 3, 2);
INSERT INTO ATTRIBUTE_VALUE (DATA, IS_ACTIVE, ATTRIBUTE_ID, PRODUCT_ID) VALUES ('Reliance', TRUE, 3, 1);

INSERT INTO ATTRIBUTE_VALUE (DATA, IS_ACTIVE, ATTRIBUTE_ID, PRODUCT_ID) VALUES ('OmniRetail', TRUE, 4, 1);
INSERT INTO ATTRIBUTE_VALUE (DATA, IS_ACTIVE, ATTRIBUTE_ID, PRODUCT_ID) VALUES ('OmniRetail', TRUE, 4, 6);
INSERT INTO ATTRIBUTE_VALUE (DATA, IS_ACTIVE, ATTRIBUTE_ID, PRODUCT_ID) VALUES ('OmniRetail', TRUE, 4, 1);
INSERT INTO ATTRIBUTE_VALUE (DATA, IS_ACTIVE, ATTRIBUTE_ID, PRODUCT_ID) VALUES ('OmniRetail', TRUE, 4, 1);
INSERT INTO ATTRIBUTE_VALUE (DATA, IS_ACTIVE, ATTRIBUTE_ID, PRODUCT_ID) VALUES ('RetailNet', TRUE, 4, 3);
INSERT INTO ATTRIBUTE_VALUE (DATA, IS_ACTIVE, ATTRIBUTE_ID, PRODUCT_ID) VALUES ('IndianSilk', TRUE, 4, 3);
INSERT INTO ATTRIBUTE_VALUE (DATA, IS_ACTIVE, ATTRIBUTE_ID, PRODUCT_ID) VALUES ('RiverHill', TRUE, 4, 4);
INSERT INTO ATTRIBUTE_VALUE (DATA, IS_ACTIVE, ATTRIBUTE_ID, PRODUCT_ID) VALUES ('BookMyWish', TRUE, 4, 2);

INSERT INTO ATTRIBUTE_VALUE (DATA, IS_ACTIVE, ATTRIBUTE_ID, PRODUCT_ID) VALUES ('599', TRUE, 5, 1);
INSERT INTO ATTRIBUTE_VALUE (DATA, IS_ACTIVE, ATTRIBUTE_ID, PRODUCT_ID) VALUES ('699', TRUE, 5, 2);
INSERT INTO ATTRIBUTE_VALUE (DATA, IS_ACTIVE, ATTRIBUTE_ID, PRODUCT_ID) VALUES ('145', TRUE, 5, 3);
INSERT INTO ATTRIBUTE_VALUE (DATA, IS_ACTIVE, ATTRIBUTE_ID, PRODUCT_ID) VALUES ('299', TRUE, 5, 4);
INSERT INTO ATTRIBUTE_VALUE (DATA, IS_ACTIVE, ATTRIBUTE_ID, PRODUCT_ID) VALUES ('999', TRUE, 5, 5);
INSERT INTO ATTRIBUTE_VALUE (DATA, IS_ACTIVE, ATTRIBUTE_ID, PRODUCT_ID) VALUES ('2025', TRUE, 5, 5);
INSERT INTO ATTRIBUTE_VALUE (DATA, IS_ACTIVE, ATTRIBUTE_ID, PRODUCT_ID) VALUES ('450', TRUE, 5, 4);
INSERT INTO ATTRIBUTE_VALUE (DATA, IS_ACTIVE, ATTRIBUTE_ID, PRODUCT_ID) VALUES ('817', TRUE, 5, 2);
INSERT INTO ATTRIBUTE_VALUE (DATA, IS_ACTIVE, ATTRIBUTE_ID, PRODUCT_ID) VALUES ('801', TRUE, 5, 3);
INSERT INTO ATTRIBUTE_VALUE (DATA, IS_ACTIVE, ATTRIBUTE_ID, PRODUCT_ID) VALUES ('350', TRUE, 5, 3);

INSERT INTO CATEGORY (NAME, DESCRIPTION, IS_ACTIVE, PRODUCT_ID) VALUES ('Shirt', 'Men Solid Casual Spread Shirt', TRUE, 1);
INSERT INTO CATEGORY (NAME, DESCRIPTION, IS_ACTIVE, PRODUCT_ID) VALUES ('Trousers', 'Slim Fit Men Beige Pure Cotton Trousers', TRUE, 2);
INSERT INTO CATEGORY (NAME, DESCRIPTION, IS_ACTIVE, PRODUCT_ID) VALUES ('EthicWear', 'Women Printed, Embellished, Checkered Rayon Straight Kurta', TRUE, 3);
INSERT INTO CATEGORY (NAME, DESCRIPTION, IS_ACTIVE, PRODUCT_ID) VALUES ('Caps', 'Embroidered CAP', TRUE, 4);
INSERT INTO CATEGORY (NAME, DESCRIPTION, IS_ACTIVE, PRODUCT_ID) VALUES ('Socks', 'Men & Women Solid Ankle Length  (Pack of 3)', TRUE, 5);
INSERT INTO CATEGORY (NAME, DESCRIPTION, IS_ACTIVE, PRODUCT_ID) VALUES ('TShirt', 'Mens Casual Half Sleeved, Striped TShirt', TRUE, 1);
INSERT INTO CATEGORY (NAME, DESCRIPTION, IS_ACTIVE, PRODUCT_ID) VALUES ('Pants', 'Men Blue Pure Denims Stylish Jeans', TRUE, 2);
INSERT INTO CATEGORY (NAME, DESCRIPTION, IS_ACTIVE, PRODUCT_ID) VALUES ('Kurtas', 'Women Printed, Embellished, Checkered Rayon Straight Kurta', TRUE, 3);